definitions:
  controllers.HealthResponse:
    properties:
      detail:
        type: string
      head:
        type: integer
      status:
        type: string
    type: object
  controllers.VersionResponse:
    properties:
      commit:
        type: string
      enabled_features:
        items:
          type: string
        type: array
      version:
        type: string
    type: object
  dto.Blob:
    properties:
      blob:
        items:
          type: integer
        type: array
      index:
        type: integer
      kzg_commitment:
        items:
          type: integer
        type: array
      kzg_commitment_inclusion_proof:
        items:
          items:
            type: integer
          type: array
        type: array
      kzg_proof:
        items:
          type: integer
        type: array
      signed_block_header:
        $ref: '#/definitions/dto.SignedBlockHeader'
    type: object
  dto.Message:
    properties:
      body_root:
        items:
          type: integer
        type: array
      parent_root:
        items:
          type: integer
        type: array
      proposer_index:
        type: integer
      slot:
        type: integer
      state_root:
        items:
          type: integer
        type: array
    type: object
  dto.SignedBlockHeader:
    properties:
      message:
        $ref: '#/definitions/dto.Message'
      signature:
        items:
          type: integer
        type: array
    type: object
  response.ApiDataResponse:
    properties:
      data: {}
      meta: {}
    type: object
  response.ApiError:
    properties:
      code:
        type: string
      detail:
        type: string
      status:
        type: integer
    type: object
  response.ApiErrorResponse:
    properties:
      errors:
        items:
          $ref: '#/definitions/response.ApiError'
        type: array
    type: object
host: localhost:8080
info:
  contact: {}
  description: Use this API to get EIP-4844 blobs as a drop-in replacement for Consensus
    Layer clients API.
  title: Ethereum Blobs REST API
  version: "1.0"
paths:
  /eth/v1/beacon/blob_sidecars/{block_id}:
    get:
      parameters:
      - description: 'Block identifier. Can be one of: ''head'', slot number, hex
          encoded blockRoot with 0x prefix'
        in: path
        name: block_id
        required: true
        type: string
      - collectionFormat: csv
        description: Array of indices for blob sidecars to request for in the specified
          block. Returns all blob sidecars in the block if not specified.
        in: query
        items:
          type: string
        name: indices
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            allOf:
            - $ref: '#/definitions/response.ApiDataResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/dto.Blob'
                  type: array
              type: object
        "400":
          description: "invalid_slot\"\t\"Invalid block id"
          schema:
            $ref: '#/definitions/response.ApiErrorResponse'
        "404":
          description: "slot_not_found\"\t\"Slot not found"
          schema:
            $ref: '#/definitions/response.ApiErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiErrorResponse'
      summary: Get Blobs by block id
      tags:
      - blobs
  /health:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.HealthResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiErrorResponse'
      summary: Returns health status of this API.
      tags:
      - health
  /version:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.ApiDataResponse'
            - properties:
                data:
                  $ref: '#/definitions/controllers.VersionResponse'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiErrorResponse'
      summary: Returns the version, commit hash and enabled features of this API.
      tags:
      - version
schemes:
- http
- https
swagger: "2.0"
