// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/eth/v1/beacon/blob_sidecars/{block_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "blobs"
                ],
                "summary": "Get Blobs by block id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Block identifier. Can be one of: ",
                        "name": "block_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ApiDataResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.Blob"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "invalid_block_id\"\t\"Invalid block_id",
                        "schema": {
                            "$ref": "#/definitions/response.ApiErrorResponse"
                        }
                    },
                    "404": {
                        "description": "blobs_not_found\"\t\"No blobs found",
                        "schema": {
                            "$ref": "#/definitions/response.ApiErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ApiErrorResponse"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "version"
                ],
                "summary": "Returns the version, commit hash and enabled features of this API.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ApiDataResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/controllers.VersionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ApiErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.VersionResponse": {
            "type": "object",
            "properties": {
                "commit": {
                    "type": "string"
                },
                "enabled_features": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "dto.Blob": {
            "type": "object",
            "properties": {
                "blob": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "extra": {
                    "$ref": "#/definitions/dto.Extra"
                },
                "index": {
                    "type": "integer"
                },
                "kzg_commitment": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "kzg_commitment_inclusion_proof": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        }
                    }
                },
                "kzg_proof": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "signed_block_header": {
                    "$ref": "#/definitions/dto.SignedBlockHeader"
                }
            }
        },
        "dto.Extra": {
            "type": "object",
            "properties": {
                "block_number": {
                    "type": "integer"
                },
                "root": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "timestamp": {
                    "$ref": "#/definitions/dto.Timestamp"
                }
            }
        },
        "dto.Message": {
            "type": "object",
            "properties": {
                "body_root": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "parent_root": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "proposer_index": {
                    "type": "integer"
                },
                "slot": {
                    "type": "integer"
                },
                "state_root": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "dto.SignedBlockHeader": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/dto.Message"
                },
                "signature": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "dto.Timestamp": {
            "type": "object",
            "properties": {
                "nanos": {
                    "type": "integer"
                },
                "seconds": {
                    "type": "integer"
                }
            }
        },
        "response.ApiDataResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "meta": {}
            }
        },
        "response.ApiError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "detail": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "response.ApiErrorResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.ApiError"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{"http", "https"},
	Title:            "Ethereum Consensus Layer Blobs REST API",
	Description:      "This is the API for Ethereum Blobs.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
