version: '3'

env:
  ENDPOINT: goerli-cl.substreams.pinax.network:443

tasks:
  protogen:
    desc: "Generates Rust types for substreams from protobuf files"
    cmds:
      - substreams protogen ./substreams.yaml --exclude-paths="sf/substreams,google,substreams/sink"

  build:
    desc: "Builds the substreams module"
    cmds:
      - cargo build --target wasm32-unknown-unknown --release

  pack:
    desc: "Pack the substreams module into SPKG file"
    deps:
      - build
    cmds:
      - substreams pack substreams.yaml

  run:
    desc: "Runs the substreams module"
    deps:
      - build
    cmds:
      - substreams run -e $ENDPOINT map_blobs -s -10

  gui:
    desc: "Runs the substreams module with the GUI"
    deps:
      - build
    cmds:
      - substreams gui -e $ENDPOINT map_blobs -s -10

  gui:graph:
    desc: "Runs the substreams graph_out module with the GUI"
    deps:
      - build
    cmds:
      - substreams gui -e $ENDPOINT graph_out -s -10

  sink:
    desc: "Sinks substreams module into KV store"
    deps:
      - build
    cmds:
      - substreams-sink-kv inject
        $ENDPOINT
        badger3://./blobs.db
        substreams.yaml
        --server-listen-addr=:8000
        --flush-interval=100
        --undo-buffer-size=1

  sink:serve:
    desc: "Serve sunk data from KV store"
    deps:
      - build
    cmds:
      - substreams-sink-kv serve badger3://./blobs.db substreams.yaml --listen-addr=:8000

  start:docker:
    desc: "Starts the substreams module in a Docker container"
    cmds:
      - docker run
        -p 8000:8000
        -e SUBSTREAMS_API_TOKEN=$SUBSTREAMS_API_TOKEN
        -v $(pwd)/blobs.db:/app/blobs.db
        ghcr.io/streamingfast/substreams-sink-kv:b38cd28
        inject
        $ENDPOINT
        badger3:///app/blobs.db
        https://github.com/pinax-network/eth-blobs/releases/download/v0.7.0/eth-blobs-v0.7.0.spkg
        --server-listen-addr=:8000
        --undo-buffer-size=1
