// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KvOperations {
    #[prost(message, repeated, tag="1")]
    pub operations: ::prost::alloc::vec::Vec<KvOperation>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KvOperation {
    #[prost(string, tag="1")]
    pub key: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub value: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="3")]
    pub ordinal: u64,
    #[prost(enumeration="kv_operation::Type", tag="4")]
    pub r#type: i32,
}
/// Nested message and enum types in `KVOperation`.
pub mod kv_operation {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Type {
        /// Protobuf default should not be used, this is used so that the consume can ensure that the value was actually specified
        Unset = 0,
        Set = 1,
        Delete = 2,
    }
    impl Type {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Type::Unset => "UNSET",
                Type::Set => "SET",
                Type::Delete => "DELETE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNSET" => Some(Self::Unset),
                "SET" => Some(Self::Set),
                "DELETE" => Some(Self::Delete),
                _ => None,
            }
        }
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Config {
    #[prost(int64, tag="1")]
    pub start_block: i64,
    #[prost(string, tag="2")]
    pub input_module: ::prost::alloc::string::String,
}
/// This defines a KV Sink to be queried with a generic key access interface (Get, GetMany, Scan, Prefix calls).
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GenericService {
    #[prost(message, optional, tag="1")]
    pub sink_config: ::core::option::Option<Config>,
}
/// This defines configuration to run a WASM query service on top of the KV store being sync'd.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WasmQueryService {
    #[prost(message, optional, tag="1")]
    pub sink_config: ::core::option::Option<Config>,
    /// wasm exports: "kv_get_batch", "kv_get", "kv_scan", "kv_prefix"
    #[prost(bytes="vec", tag="5")]
    pub wasm_query_module: ::prost::alloc::vec::Vec<u8>,
    /// Fully qualified Protobuf Service definition name
    ///
    /// sf.mycustom.v1.MyService
    #[prost(string, tag="2")]
    pub grpc_service: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
