# Workflow to build the application and run unit tests on every push and PR.
name: Build & Tests

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [ 1.25.x ]
        os: [ ubuntu-latest ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
          cache: true
          cache-dependency-path: "**go.sum"

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        working-directory: api-service
        run: task build

      - name: Test
        working-directory: api-service
        run: task test
